---

- name: Get PostgreSQL apt repo key.
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
           id=ACCC4CF8
           state=present

- name: Add PostgreSQL apt repo.
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ postgresql_distro_version }}-pgdg main'
                  state=present

- name: Install PostgreSQL.
  apt: name=postgresql-{{ postgresql_version }}

- name: Install PostgreSQL python module.
  apt: name=python-pyscopg2

- name: Make sure db is running.
  service: name=postgresql state=started
