---

- name: Get PostgreSQL apt repo key.
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
           id=ACCC4CF8
           state=present

- name: Add PostgreSQL apt repo.
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ postgresql_distro_version }}-pgdg main'
                  state=present

- name: Install PostgreSQL.
  apt: name={{ item }}
  with_items:
    - postgresql-{{ postgresql_version }}
    - postgresql-server-dev-{{ postgresql_version }}
    - python-dev

- name: Install PostgreSQL python module.
  pip: name=psycopg2

- name: Make sure db is running.
  service: name=postgresql state=started

- name: Create database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ postgresql_database }}
                 state=present
                 login_unix_socket='/var/run/postgresql'
  when: postgresql_database is defined

- name: Create db user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ postgresql_user }}
                   password={{ postgresql_password }}
                   login_unix_socket='/var/run/postgresql'
  when: postgresql_user is defined
